dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install --upgrade pytest flake8
script:
  - python setup.py develop
  - if [[ $TRAVIS_PYTHON_VERSION > "2.6" ]]; then flake8; fi
  - py.test
