dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install --upgrade pip
  - pip install --upgrade pytest flake8
script:
  - python setup.py develop
  - flake8
  - py.test
